version: 2.0

use_jdk_8: &use_jdk_8
  docker:
    - image: circleci/openjdk:8-jdk

use_jdk_11: &use_jdk_11
  docker:
    - image: circleci/openjdk:11-jdk

use_environment: &use_environment
  working_directory: ~/repo

  environment:
    JVM_OPTS: -Xmx3200m
    TERM: dumb

run_tests_steps: &run_tests_steps
  - checkout

  - restore_cache:
      keys:
        - v1-dependencies-{{ checksum "build.sbt" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

  - run: cat /dev/null | ./sbt +update

  - save_cache:
      paths:
        - ~/.m2
      key: v1-dependencies--{{ checksum "build.sbt" }}

  - run:
      name: Run Tests
      command: cat /dev/null | ./sbt check

jobs:
  test_jdk_8:
    <<: *use_jdk_8
    <<: *use_environment
    steps:
      <<: *run_tests_steps

  test_jdk_11:
    <<: *use_jdk_11
    <<: *use_environment
    steps:
      <<: *run_tests_steps

  release:
    <<: *use_jdk_11
    <<: *use_environment
    steps:
      - checkout

      - run:
          name: Fetch git tags
          command: git fetch --tags

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: cat /dev/null | ./sbt +update

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}

      - run:
          name: Decrypt secrets
          command: ./.secrets/decrypt.sh "${AES_KEY}"

      - run:
          name: Release to Sonatype
          command: ./sbt +releaseEarly

workflows:
  version: 2
  build:
    jobs:
      - test_jdk_8
      - test_jdk_11
      - release:
          filters:
            branches:
              only: master
          context: org-global
          requires:
            - test_jdk_11
