package au.id.tmm.intime.std

object implicits
    extends AnyRef
    with instances.InstanceTraits.DurationInstances
    with syntax.DurationOps.ToDurationOps
    with instances.InstanceTraits.InstantInstances
    with syntax.InstantOps.ToInstantOps
    with instances.InstanceTraits.LocalDateInstances
    with syntax.LocalDateOps.ToLocalDateOps
    with instances.InstanceTraits.LocalDateTimeInstances
    with syntax.LocalDateTimeOps.ToLocalDateTimeOps
    with instances.InstanceTraits.LocalTimeInstances
    with syntax.LocalTimeOps.ToLocalTimeOps
    with instances.InstanceTraits.OffsetDateTimeInstances
    with syntax.OffsetDateTimeOps.ToOffsetDateTimeOps
    with instances.InstanceTraits.OffsetTimeInstances
    with syntax.OffsetTimeOps.ToOffsetTimeOps
    with instances.PeriodInstances
    with syntax.PeriodOps.ToPeriodOps
    with instances.InstanceTraits.YearInstances
    with syntax.YearOps.ToYearOps
    with instances.InstanceTraits.YearMonthInstances
    with syntax.YearMonthOps.ToYearMonthOps
    with instances.InstanceTraits.ZonedDateTimeInstances
    with syntax.ZonedDateTimeOps.ToZonedDateTimeOps
