package au.id.tmm.intime.cats

object implicits
    extends AnyRef
    with instances.DayOfWeekInstances
    with instances.DurationInstances
    with instances.InstantInstances
    with instances.LocalDateInstances
    with instances.LocalDateTimeInstances
    with instances.LocalTimeInstances
    with instances.MonthDayInstances
    with instances.MonthInstances
    with instances.OffsetDateTimeInstances
    with instances.OffsetTimeInstances
    with instances.PeriodInstances
    with instances.YearInstances
    with instances.YearMonthInstances
    with instances.ZonedDateTimeInstances
    with instances.ZoneIdInstances
    with instances.ZoneOffsetInstances
